
val coinList = listOf("TRXUSDT", "LINKUSDT", "ZILUSDT", "GRTUSDT", "CRVUSDT", "RLCUSDT", "LINAUSDT", "ALICEUSDT", "ANKRUSDT", "APEUSDT", "APTUSDT", "ARUSDT", "AUDIOUSDT",
    "RNDRUSDT", "LUNCUSDT", "SUIUSDT","DASHUSDT", "COCOSUSDT", "FILUSDT", "FLOWUSDT", "FXSUSDT","PEPEUSDT", "TWTUSDT", "WOOUSDT", "GNOUSDT", "MASKUSDT",
    "FETUSDT", "EPXUSDT", "ENSUSDT", "GALAUSDT", "KAVAUSDT", "LUNAUSDT", "LITUSDT", "OGNUSDT", "ONTUSDT", "XMRUSDT", "APTUSDT", "OPUSDT",
    "BTCUSDT", "ADAUSDT", "AVAXUSDT", "ETHUSDT", "SOLUSDT", "DOTUSDT", "SHIBUSDT",
    "ATOMUSDT", "NEOUSDT", "FTMUSDT", "SYSUSDT", "ROSEUSDT",
    "C98USDT","FILUSDT", "XRPUSDT", "DOGEUSDT", "LTCUSDT", "BCHUSDT", "XLMUSDT", "TFUELUSDT", "AAVEUSDT", "RENUSDT",
    "THETAUSDT", "VETUSDT", "ETCUSDT", "EOSUSDT", "ICPUSDT", "MATICUSDT", "MASKUSDT", "ALGOUSDT", "AXSUSDT", "EGLDUSDT", "STXUSDT",
    "SUSHIUSDT", "SNXUSDT", "KSMUSDT", "BATUSDT", "OMGUSDT", "XTZUSDT", "BANDUSDT", "RUNEUSDT", "ICXUSDT", "HNTUSDT", "QTUMUSDT",
    "ZRXUSDT", "LRCUSDT", "KNCUSDT", "BALUSDT", "OXTUSDT", "NMRUSDT", "ENJUSDT", "STORJUSDT", "SCUSDT",
    "MANAUSDT", "REPUSDT", "SXPUSDT", "ANTUSDT", "WTCUSDT", "BTSUSDT", "NEARUSDT", "SANDUSDT", "RSRUSDT", "FIOUSDT", "OCEANUSDT", "CHZUSDT", "WINGUSDT",
    "BNTUSDT", "DGBUSDT", "1INCHUSDT", "BZRXUSDT",
    "STMXUSDT", "SRMUSDT", "GXSUSDT", "ZENUSDT", "KMDUSDT", "IOSTUSDT", "DENTUSDT", "WANUSDT", "CVCUSDT", "WAVESUSDT", "REPUSDT",
    "CAKEUSDT", "CELOUSDT", "AVAUSDT", "DEGOUSDT", "FIROUSDT", "TOMOUSDT", "EGLDUSDT", "QUICKUSDT", "UNFIUSDT")